denuncia/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from denuncia.views import DenunciaCreate, DenunciaList, \
    DenunciaDelete, DenunciaUpdate

# from django.conf import settings
# from django.conf.urls.static import static

# admin.autodiscover()

urlpatterns = [
                  url(r'^nuevo$', login_required(DenunciaCreate.as_view()), name='denuncia_crear'),
                  url(r'^listar/$', login_required(DenunciaList.as_view()), name='denuncia_listar'),
                  url(r'^editar/(?P<pk>\d+)/$', login_required(DenunciaUpdate.as_view()), name='denuncia_editar'),
                  url(r'^eliminar/(?P<pk>\d+)/$', login_required(DenunciaDelete.as_view()), name='denuncia_eliminar'),
              ]

reportes/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from reportes.views import ReportList, ReportRango, generar_pdf_rango, generar_ficha_pdfd



# from django.conf import settings
# from django.conf.urls.static import static

# admin.autodiscover()

urlpatterns = [
                  url(r'^listar', login_required(ReportList.as_view()), name='reportes_listar'),
                  url(r'^rango_f', login_required(ReportRango.as_view()), name='rango'),
                  url(r'^ficha/(?P<pk>\d+)/$', login_required(generar_ficha_pdfd), name='ficha'),
                  url(r'^rangopdf/', login_required(generar_pdf_rango), name='pdf_rango'),

              ]

sid/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings

urlpatterns = [

    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^tipo_diligencia/', include('tipo_diligencia.urls', namespace="diligencia")),
    url(r'^victima/', include('victima.urls', namespace="victima")),
    url(r'^agresor/', include('agresor.urls', namespace="agresor")),
    url(r'^procedencia_denuncia/', include('procedencia_denuncia.urls', namespace="procedencia")),
    url(r'^derechos/', include('derechos.urls', namespace="derechos")),
    url(r'^denuncia/', include('denuncia.urls', namespace="denuncia")),
    url(r'^reportes/', include('reportes.urls', namespace="reportes")),
    url(r'^admin/', admin.site.urls)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)


denuncia/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from tipo_diligencia.models import Diligencia
from procedencia_denuncia.models import Procedencia
from victima.models import Victima
from agresor.models import Agresor
from derechos.models import Derecho

# Create your models here.

SELECCION_TIPO = (

    ('I', 'Inicial'),
)
class Correlativo(models.Model):

 correlative = models.IntegerField('Correlativo:', help_text='Ingrese el Correlativo Inicial')

 def __unicode__(self):
  return '%s' % self.correlative

 class META:
    verbose_name = 'Correlativo'
    verbose_plural_name = 'Correlativos'


class Denuncia(models.Model):

 fechadenuncia= models.DateField('Fecha de Denuncia', help_text='Ingrese Fecha en que se realiza la denuncia')
 diligencia = models.ForeignKey(Diligencia, verbose_name='Diligencia')
 procedencia = models.ForeignKey(Procedencia, verbose_name='Procedencia')
 victima = models.ForeignKey(Victima, verbose_name='Victima')
 Agresor = models.ForeignKey(Agresor, verbose_name='Agresor')
 derecho = models.ForeignKey(Derecho, verbose_name='Derecho')
 status = models.BooleanField('Estado del la denuncia', default=False,
                              help_text='Indique el estado de la denuncia')
 carpeta = models.CharField('No. De Carpeta Judicial:', max_length=15,
                           help_text='Indique el número de carpeta judicial')
 description = models.TextField('Descripción', max_length=3500,
                           help_text='Descripción de la denuncia')
 created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Creado')
 modified = models.DateTimeField(auto_now=True, editable=False, verbose_name='Modificado')
 correlativo = models.IntegerField(editable=False, blank=True, null=True)

 def save(self, *args, **kwargs):  # redefinicion del metodo save() que contiene nuestro trigger

     if Denuncia.objects.all().count() == 0:
         codigo = Correlativo.objects.get().correlative
         if self.correlativo is None:
             res1 = 0
         else:
             res1 = codigo
         self.correlativo = res1 + codigo
     else:
         cor = Denuncia.objects.all()[Denuncia.objects.count()-1].correlativo
         self.correlativo = cor + 1
     # Aqui ponemos el codigo del trigger -------
     # fin de trigger ------
     return super(Denuncia, self).save(*args,
                                       **kwargs)  # llamada al save() original con sus parámetros correspondientes


 def __unicode__(self):
  return '%s' % self.correlativo


 class META:
    verbose_name = 'Denuncia'
    verbose_plural_name = 'Denuncias'


denuncia/forms.py
# -*- coding: utf-8 -*-
from django import forms
from denuncia.models import Denuncia

class DateInput(forms.DateInput):
    input_type = 'date'
    format = ('d-m-Y')


class DenunciaForm(forms.ModelForm):
    class Meta:
        model = Denuncia

        fields = [
            'fechadenuncia',
            'victima',
            'Agresor',
            'derecho',
            'status',
            'diligencia',
            'procedencia',
            'carpeta',
            'description',
        ]

        labels = {
            'fechadenuncia': 'Fecha de Denuncia:',
            'victima': 'Victima:',
            'Agresor': 'Agresor:',
            'derecho': 'Derecho Vulnerado:',
            'status': 'Estado de la Denuncia:',
            'diligencia': 'Diligencia Correspondiente:',
            'procedencia':'Tipo de Procedencia',
            'carpeta': 'No. De Carpeta Judicial:',
            'description': 'Ingrese una Descripción de la Denuncia:',
        }

        widgets = {
            'fechadenuncia':   DateInput(attrs={'class': 'form-control'}),
            'victima': forms.Select(attrs={'class': 'form-control'}),
            'Agresor': forms.Select(attrs={'class': 'form-control'}),
            'derecho': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.CheckboxInput(attrs={'class': 'form-control'}),
            'diligencia': forms.Select(attrs={'class': 'form-control'}),
            'procedencia': forms.Select(attrs={'class': 'form-control'}),
            'carpeta': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

denuncia/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Q
import operator
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator

from denuncia.forms import DenunciaForm
from denuncia.models import Denuncia
from victima.models import Victima
from victima.forms import VictimaForm


# Create your views here
class DenunciaList(ListView):
    model = Denuncia
    template_name = 'crud/denuncia/denuncia_listar.html'
    paginate_by = 10
    ordering = ["-id"]

    def get_queryset(self):
        result = super(DenunciaList, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(correlativo__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(procedencia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(victima__icontains=q) for q in query_list))
            )

        return result

    @method_decorator(
        permission_required('denuncia.add_denuncia', reverse_lazy('dashboard:dashboard_inicio')))
    def dispatch(self, *args, **kwargs):
        return super(DenunciaList, self).dispatch(*args, **kwargs)



class DenunciaCreate(CreateView):
    model = Denuncia
    form_class = DenunciaForm
    template_name = 'crud/denuncia/denuncia_form.html'
    success_url = reverse_lazy('denuncia:denuncia_listar')


    @method_decorator(
        permission_required('denuncia.add_denuncia', reverse_lazy('dashboard:dashboard_inicio')))
    def dispatch(self, *args, **kwargs):
        return super(DenunciaCreate, self).dispatch(*args, **kwargs)


class DenunciaUpdate(UpdateView):
    model = Denuncia
    form_class = DenunciaForm
    template_name = 'crud/denuncia/denuncia_form.html'
    success_url = reverse_lazy('denuncia:denuncia_listar')


class DenunciaDelete(DeleteView):
    model = Denuncia
    template_name = 'crud/denuncia/denuncia_eliminar.html'
    success_url = reverse_lazy('denuncia:denuncia_listar')


templates/crud/denuncia/denuncia_eliminar.html
{% extends "main_crud.html" %}
{% load static %}

{% block content %}
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Eliminar Denuncia</h1>
                    </div>
                    <!-- /.col-lg-12 -->

                </div>
                <!-- /.row -->

            </div>
            <form method="post">
                    {% csrf_token %}
                <h4>Desea Eliminar Denuncia: {{ object.correlativo }} ?</h4>
                    <button type="submit" class="btn btn-danger">SÍ, ELIMINAR</button>
                    <a class="btn btn-default" href="{% url 'denuncia:denuncia_listar' %}">CANCELAR</a>
                </form>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

{% endblock %}

templates/crud/denuncia/denuncia_form.html
{% extends "main_crud.html" %}
{% load static %}

{% block content %}
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header" align="center">Denuncias</h1>
                    </div>
                    <!-- /.col-lg-12 -->

                </div>
                <!-- /.row -->

            </div>
            <form method="post">
                    {% csrf_token %}
                    <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="form-group">
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">GUARDAR</button>
                            </div>
                        </div>
                    </div>
                    </div>
                </form>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

{% endblock %}

templates/crud/denuncia/denuncia_listar.html
{% extends "main_crud.html" %}
{% load static %}

{% block content %}
<!-- Page Content -->

        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Denuncias</h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <form method="get" action="{% url 'denuncia:denuncia_listar' %}"  class="navbar-form pull-right">
                        <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="Buscar">
                        <input type="submit" class="btn" value="Buscar" >
                </form>
                <!-- /.row -->
                <table class="table table-bordered">
                <a class="btn btn-primary btn-sm" href="{% url "denuncia:denuncia_crear" %}">(+) Nuevo</a>
                    <thead>
                    <tr>
                        <td align="center" bgcolor="#eeeeee">Correlativo</td>
                        <td align="center" bgcolor="#eeeeee">Victima</td>
                        <td align="center" bgcolor="#eeeeee">Agresor</td>
                        <td align="center" bgcolor="#eeeeee">Derecho Vulnerado</td>
                        <td align="center" bgcolor="#eeeeee">Estado de Denuncia</td>
                        <td align="center" bgcolor="#eeeeee">Diligencia</td>
                        <td align="center" bgcolor="#eeeeee">Procedencia</td>
                        <td align="center" bgcolor="#eeeeee">Carpeta</td>
                        <td align="center" bgcolor="#eeeeee">ACCIÓN</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% if object_list %}
                    {% for denuncia in object_list %}
                    <tr>
                        <td align="center">{{ denuncia.correlativo}}</td>
                        <td align="center">{{ denuncia.victima }}</td>
                        <td align="center">{{ denuncia.Agresor }}</td>
                        <td align="center">{{ denuncia.derecho }}</td>
                        <td align="center">{{ denuncia.status }}</td>
                        <td align="center">{{ denuncia.diligencia }}</td>
                        <td align="center">{{ denuncia.procedencia}}</td>
                        <td align="center">{{ denuncia.carpeta }}</td>
                        <td align="center" bgcolor="#eeeeee">
                            {% if perms.denuncia.change_denuncia %}
                            <a class="btn btn-success btn-xs" href="{% url "denuncia:denuncia_editar" denuncia.id %}">Editar</a>
                            {% endif %}
                            {% if perms.denuncia.delete_denuncia %}
                            <a class="btn btn-warning btn-xs" href="{% url "denuncia:denuncia_eliminar" denuncia.id %}">Eliminar</a>
                            {% endif %}
                            {% if perms.denuncia.add_denuncia %}
                            <a class="btn btn-warning btn-xs" href="{% url "reportes:ficha" denuncia.id %}">FICHA</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <h3>No Hay Registros de Denuncias...</h3>
                    {% endif %}
                    </tbody>
                </table>
                <ul class="pager">
                    <li>
                        {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number}}">Anterior</a>
                        {% endif %}
                    </li>
                        <span class="actual">
                         Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
                         </span>
                    <li>
                        {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number}}">Siguiente</a>
                        {% endif %}
                    </li>
                 </ul>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

{% endblock %}