sid/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings

urlpatterns = [

    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^tipo_diligencia/', include('tipo_diligencia.urls', namespace="diligencia")),
    url(r'^victima/', include('victima.urls', namespace="victima")),
    url(r'^agresor/', include('agresor.urls', namespace="agresor")),
    url(r'^procedencia_denuncia/', include('procedencia_denuncia.urls', namespace="procedencia")),
    url(r'^derechos/', include('derechos.urls', namespace="derechos")),
    url(r'^denuncia/', include('denuncia.urls', namespace="denuncia")),
    url(r'^reportes/', include('reportes.urls', namespace="reportes")),
    url(r'^admin/', admin.site.urls)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)


tipo_diligencia/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from tipo_diligencia.views import DiligenciaList, DiligenciaCreate, \
    DiligenciaUpdate, DiligenciaDelete, DenunciaDiligenciaCreate

# from django.conf import settings
# from django.conf.urls.static import static

# admin.autodiscover()

urlpatterns = [
                  url(r'^nuevo$', login_required(DiligenciaCreate.as_view()), name='diligencia_crear'),
                  url(r'^listar/$', login_required(DiligenciaList.as_view()), name='diligencia_listar'),
                  url(r'^editar/(?P<pk>\d+)/$', login_required(DiligenciaUpdate.as_view()), name='diligencia_editar'),
                  url(r'^eliminar/(?P<pk>\d+)/$', login_required(DiligenciaDelete.as_view()), name='diligencia_eliminar'),
                  url(r'^nuevo_para_denuncia/$', login_required(DenunciaDiligenciaCreate.as_view()), name='dediladd'),
              ]

templates/crud/Diligencia/diligencia_eliminar.html
{% extends "main_crud.html" %}
{% load static %}

{% block content %}
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Eliminar Diligencia</h1>
                    </div>
                    <!-- /.col-lg-12 -->

                </div>
                <!-- /.row -->

            </div>
            <form method="post">
                    {% csrf_token %}
                <h4>Desea Eliminar la Diligencia: {{ object.nombre }} ?</h4>
                    <button type="submit" class="btn btn-danger">SÍ, ELIMINAR</button>
                    <a class="btn btn-default" href="{% url 'diligencia:diligencia_listar' %}">CANCELAR</a>
                </form>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

{% endblock %}

templates/crud/Diligencia/diligencia_form.html
{% extends "main_crud.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header" align="center">Ingreso de Diligencia</h1>
                    </div>
                </div>
            </div>
<form method="post" action="" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{form.nombre.name}}">{{form.nombre.label}}</label>
                {{form.nombre}}
            </div>
        </div>

    </div>
    <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <button class="btn btn-primary" type="submit" selected="selected">GUARDAR</button>
            </div>
        </div>
</form>
{% endblock %}

templates/crud/Diligencia/diligencia_form_denuncia.html
{% extends "main_crud.html" %}
{% load static %}

{% block content %}
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header" align="center">Ingreso de Encargado</h1>
                    </div>
                    <!-- /.col-lg-12 -->

                </div>
                <!-- /.row -->

            </div>
            <form method="post">
                    {% csrf_token %}
                    <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="form-group">
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary">GUARDAR</button>
                            </div>
                        </div>
                    </div>
                    </div>
                </form>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

{% endblock %}

templates/crud/Diligencia/diligencia_listar.html
{% extends "main_crud.html" %}
{% load static %}

{% block content %}
<!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-lg-12">
                        <h1 class="page-header">Diligencias</h1>
                    </div>
                    <!-- /.col-lg-12 -->

                </div>
                <form method="get" action="{% url 'diligencia:diligencia_listar' %}"  class="navbar-form pull-right">
                        <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="Search">
                        <input type="submit" class="btn" value="Search" >
                </form>
                <!-- /.row -->
                <table class="table table-bordered">
                <a class="btn btn-primary btn-sm" href="{% url "diligencia:diligencia_crear" %}">(+) Nuevo</a>
                    <thead>
                    <tr>
                        <td align="center" bgcolor="#eeeeee">Nombre</td>
                        <td align="center" bgcolor="#eeeeee">ACCIÓN</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% if object_list %}
                    {% for diligencia in object_list %}
                    <tr>
                        <td align="center">{{ diligencia.nombre }}</td>
                        <td align="center" bgcolor="#eeeeee">
                            <a class="btn btn-success btn-xs" href="{% url "diligencia:diligencia_editar" diligencia.id %}">Editar</a>
                            <a class="btn btn-warning btn-xs" href="{% url "diligencia:diligencia_eliminar" diligencia.id %}">Eliminar</a>
                        </td>

                    </tr>
                    {% endfor %}

                    {% else %}
                    <h3>No Hay Registros de Diligencias...</h3>
                    {% endif %}
                    </tbody>
                </table>
                <ul class="pager">
                    <li>
                        {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number}}">Anterior</a>
                        {% endif %}
                    </li>
                    <li>
                        {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number}}">Siguiente</a>
                        {% endif %}
                    </li>
                 </ul>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

{% endblock %}