agresor/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from agresor.views import AgresorList, \
    AgresorUpdate, AgresorDelete, AgresorCrear


urlpatterns = [
                  url(r'^nuevo', login_required(AgresorCrear.as_view()), name='agresor_crear'),
                  url(r'^listar', login_required(AgresorList.as_view()), name='agresor_listar'),
                  url(r'^editar/(?P<pk>\d+)/$', login_required(AgresorUpdate.as_view()), name='agresor_editar'),
                  url(r'^eliminar/(?P<pk>\d+)/$', login_required(AgresorDelete.as_view()), name='agresor_eliminar'),
              ]

denuncia/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from denuncia.views import DenunciaCreate, DenunciaList, \
    DenunciaDelete, DenunciaUpdate

# from django.conf import settings
# from django.conf.urls.static import static

# admin.autodiscover()

urlpatterns = [
                  url(r'^nuevo$', login_required(DenunciaCreate.as_view()), name='denuncia_crear'),
                  url(r'^listar/$', login_required(DenunciaList.as_view()), name='denuncia_listar'),
                  url(r'^editar/(?P<pk>\d+)/$', login_required(DenunciaUpdate.as_view()), name='denuncia_editar'),
                  url(r'^eliminar/(?P<pk>\d+)/$', login_required(DenunciaDelete.as_view()), name='denuncia_eliminar'),
              ]

derechos/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from derechos.views import DerechoList, DerechoCreate, \
    DerechoUpdate, DerechoDelete, DerechoDenunciaCreate

# from django.conf import settings
# from django.conf.urls.static import static

# admin.autodiscover()

urlpatterns = [
                  url(r'^nuevo$', login_required(DerechoCreate.as_view()), name='derecho_crear'),
                  url(r'^listar/$', login_required(DerechoList.as_view()), name='derecho_listar'),
                  url(r'^editar/(?P<pk>\d+)/$', login_required(DerechoUpdate.as_view()), name='derecho_editar'),
                  url(r'^eliminar/(?P<pk>\d+)/$', login_required(DerechoDelete.as_view()), name='derecho_eliminar'),
                  url(r'^nuevo_para_denuncia/$', login_required(DerechoDenunciaCreate.as_view()), name='dediladd'),
              ]

sid/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout_then_login
from django.conf import settings

urlpatterns = [

    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/', login, {'template_name': 'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard")),
    url(r'^tipo_diligencia/', include('tipo_diligencia.urls', namespace="diligencia")),
    url(r'^victima/', include('victima.urls', namespace="victima")),
    url(r'^agresor/', include('agresor.urls', namespace="agresor")),
    url(r'^procedencia_denuncia/', include('procedencia_denuncia.urls', namespace="procedencia")),
    url(r'^derechos/', include('derechos.urls', namespace="derechos")),
    url(r'^denuncia/', include('denuncia.urls', namespace="denuncia")),
    url(r'^reportes/', include('reportes.urls', namespace="reportes")),
    url(r'^admin/', admin.site.urls)

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(
    settings.STATIC_URL, document_root=settings.STATIC_ROOT)


victima/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from victima.views import VictimaList, \
    VictimaUpdate, VictimaDelete, VictimaCrear, VictimaDenunciaCreate


urlpatterns = [
                  url(r'^nuevo', login_required(VictimaCrear.as_view()), name='victima_crear'),
                  url(r'^listar', login_required(VictimaList.as_view()), name='victima_listar'),
                  url(r'^editar/(?P<pk>\d+)/$', login_required(VictimaUpdate.as_view()), name='victima_editar'),
                  url(r'^eliminar/(?P<pk>\d+)/$', login_required(VictimaDelete.as_view()), name='victima_eliminar'),
                  url(r'^CrearDenuncia/$', login_required(VictimaDenunciaCreate.as_view()), name='dediladd'),
              ]

templates/index.html
{% extends 'login/base.html' %}
{% load staticfiles %}
{% block title %}
SID
{% endblock %}
{% block navbar%}
{% endblock %}
{% block content %}
     <br>
        <h4><center>Bienvenido a SID (SISTEMA INTEGRAL DE DENUNCIAS 1.0)</center></h4>
        <center>
        <table>
            <tr>
                <td><center><img src="{% static 'img/lolto.jpg' %}" height="500" width="500" class='img-responsive'></center></td>
            </tr>
        </table>
        </center>

<form method="post">
	{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Nombre de usuario:</label>
        		<input class="form-control" type="text" name="username">
    	   </div>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="username">Contraseña:</label>
        		<input class="form-control" type="password" name="password">
    	   </div>
        </div>
    </div>
    <div class="row">
        <center>
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<input class="btn btn-primary" type="submit" value="Ingresar">
    	   </div>
        </div></center>
    </div>
</form>


{% endblock %}

templates/main.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block extrastatic %}
    {% endblock %}

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static "img/favicon.jpg" %}">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/custom.min.css' %}" rel="stylesheet">

    <title>{% block title %}SID v.1.0 {% endblock %}</title>

</head>

<body>

    <!-- Page Content -->
    <div class="container">
    {% block navbar %}
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                    <nav class="navbar navbar-inverse navbar-fixed-top">
                        <div <div class="container">
                            <div class="navbar-header">
                            </div>
                                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Denuncias <span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso</li>
                                                <li><a href="{% url "denuncia:denuncia_crear" %}"> Crear Denuncia</a></li>

                                        </ul>
                                    </li>
                                </ul>


                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Registros <span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso/Consulta</li>
                                                {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                <li><a href="{% url "diligencia:diligencia_crear" %}"> Registrar Diligencia </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "victima:victima_crear" %}"> </span> Registrar Victima </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "agresor:agresor_crear" %}"> Registrar Agresor </a></li>
                                                {% endif %}
                                                {% if perms.procedencia_denuncia.add_victima %}
                                                <li><a href="{% url "procedencia:procedencia_crear" %}"> Registrar Procedencia de Denuncias </a></li>
                                                {% endif %}
                                                {% if perms.derechos.add_derechos %}
                                                <li><a href="{% url "derechos:derecho_crear" %}"> Registrar Derechos Vulnerados </a></li>
                                                {% endif %}
                                                {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                {% endif %}
                                        </ul>
                                    </li>
                                </ul>

                                        <ul class="nav navbar-nav">
                                    <li class="dropdown">

                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Listados<span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso/Consulta</li>
                                                                        {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                <li><a href="{% url "diligencia:diligencia_listar" %}"> Listar Diligencia </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "victima:victima_listar" %}"> </span> Listar Victima </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "agresor:agresor_listar" %}"> Listar Agresor </a></li>
                                                {% endif %}
                                                {% if perms.procedencia_denuncia.add_victima %}
                                                <li><a href="{% url "procedencia:procedencia_listar" %}"> LIstar Procedencia de Denuncias </a></li>
                                                {% endif %}
                                                {% if perms.derechos.add_derechos %}
                                                <li><a href="{% url "derechos:derecho_listar" %}"> Listar Derechos Vulnerados </a></li>
                                                {% endif %}
                                                {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                {% endif %}

                                         </ul>
                                    </li>
                                </ul>
                                                    <ul class="nav navbar-nav">
                                    <li class="dropdown">

                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Reportes <span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso/Consulta</li>
                                             {% if user.is_superuser %}
                                            <li><a href={% url "reportes:reportes_listar" %}> Tipos de Reporte </a></li>
                                             {% endif %}



                                       </ul>
                                    </li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                    </li>
                                   <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Opciones <span class="caret"></span></a>
                                       <ul class="dropdown-menu" role="menu">
                                            {% if user.is_superuser %}
                                            <li role="presentation" class="dropdown-header">Privilegiadas</li>
                                            <li><a href="/admin"> Modo Administrador</a></li>
                                             {% endif %}
                                            <li role="presentation" class="dropdown-header">Logeo</li>
                                            <li><a href="{% url 'logout' %}"> Salir</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>


        {% endblock %}


        {% block content %}
        <br>
        <center>
        <table>
            <tr>
                <td><center><img src="{% static 'img/lolto.jpg' %}" height="600" width="600" class='img-responsive' ></center></td>
            </tr>
        </table>
        </center>

        {% endblock %}


        {% block footer %}
        {% endblock %}
    </div>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/custom.js' %}"></script>

    {% block extrajs %}
    {% endblock %}

</body>

</html>

templates/main_crud.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block extrastatic %}
    {% endblock %}

    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static "img/favicon.jpg" %}">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/custom.min.css' %}" rel="stylesheet">
{% block scripts %}{% endblock %}

    <title>{% block title %}SID v.1.0 {% endblock %}</title>

</head>

<body>

    <!-- Page Content -->
    <div class="container">
    {% block navbar %}
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                    <nav class="navbar navbar-inverse navbar-fixed-top">
                        <div <div class="container">
                            <div class="navbar-header">
                                <a class="navbar-brand" href="{% url 'dashboard:dashboard_inicio' %}"> Inicio</a>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Denuncias<span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso</li>
                                                <li><a href=""> Crear Denuncia</a></li>

                                        </ul>
                                    </li>
                                </ul>


                                <ul class="nav navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Registros <span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso/Consulta</li>
                                                {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                <li><a href="{% url "diligencia:diligencia_crear" %}"> Registrar Diligencia </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "victima:victima_crear" %}"> </span> Registrar Victima </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "agresor:agresor_crear" %}"> Registrar Agresor </a></li>
                                                {% endif %}
                                                {% if perms.procedencia_denuncia.add_victima %}
                                                <li><a href="{% url "procedencia:procedencia_crear" %}"> Registrar Procedencia de Denuncias </a></li>
                                                {% endif %}
                                                {% if perms.derechos.add_derechos %}
                                                <li><a href="{% url "derechos:derecho_crear" %}"> Registrar Derechos Vulnerados </a></li>
                                                {% endif %}
                                                {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                {% endif %}
                                        </ul>
                                    </li>
                                </ul>

                                        <ul class="nav navbar-nav">
                                    <li class="dropdown">

                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Listados<span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso/Consulta</li>
                                                                        {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                <li><a href="{% url "diligencia:diligencia_listar" %}"> Listar Diligencia </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "victima:victima_listar" %}"> </span> Listar Victima </a></li>
                                                {% endif %}
                                                {% if perms.victima.add_victima %}
                                                <li><a href="{% url "agresor:agresor_listar" %}"> Listar Agresor </a></li>
                                                {% endif %}
                                                {% if perms.procedencia_denuncia.add_victima %}
                                                <li><a href="{% url "procedencia:procedencia_listar" %}"> LIstar Procedencia de Denuncias </a></li>
                                                {% endif %}
                                                {% if perms.derechos.add_derechos %}
                                                <li><a href="{% url "derechos:derecho_listar" %}"> Listar Derechos Vulnerados </a></li>
                                                {% endif %}
                                                {% if perms.tipo_diligencia.add_tipo_diligencia %}
                                                {% endif %}

                                         </ul>
                                    </li>
                                </ul>
                                                    <ul class="nav navbar-nav">
                                    <li class="dropdown">

                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Reportes <span class="caret"></span></a>
                                         <ul class="dropdown-menu" role="menu">
                                             <li role="presentation" class="dropdown-header">Ingreso/Consulta</li>
                                             {% if user.is_superuser %}
                                            <li><a href={% url "reportes:reportes_listar" %}> Tipos de Reporte </a></li>
                                             {% endif %}
                                       </ul>
                                    </li>
                                </ul>
                        <ul class="nav navbar-nav navbar-right">
                                    <li class="dropdown">
                                    </li>
                                   <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> Opciones <span class="caret"></span></a>
                                       <ul class="dropdown-menu" role="menu">
                                            {% if user.is_superuser %}
                                            <li role="presentation" class="dropdown-header">Privilegiadas</li>
                                            <li><a href="/admin"> Modo Administrador</a></li>
                                             {% endif %}
                                            <li role="presentation" class="dropdown-header">Logeo</li>
                                            <li><a href="{% url 'logout' %}"> Salir</a></li>
                                        </ul>
                                    </li>
                                </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>


        {% endblock %}


        {% block content %}
        {% endblock %}


        {% block footer %}
        {% endblock %}
    </div>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/custom.js' %}"></script>

    {% block extrajs %}
    {% endblock %}

</body>

</html>